/*
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

package main

import "fmt"

func main() {
	fibA := 0
	fibB := 1
	fibX := 0
	limit := 4000000
	sum := 0

	for fibB < limit {
		fibX = fibA + fibB
		fibA = fibB
		fibB = fibX

		if fibA%2 == 0 {
			sum = sum + fibA
		}
	}
	fmt.Println("Answer = ", sum)
}
